### PR TITLE
Use new mount signature

### PR DESCRIPTION
**Pull request by YerkoPalma**

### CODE REVIEW

**Review by ungoldman — APPROVED** [review]
LGTM

**Review by goto-bus-stop — APPROVED** [review]

**Review by ghost — APPROVED** [review]
LGTM!

**Comment by tnguyen14** [comment]
Where is this new signature documented? Just looking to learn how the new `mount()` method behaves.

**Comment by yoshuawuyts** [comment]
@tnguyen14 probably in the source, mostly. Docs PR would be very useful though!

**Comment by tnguyen14** [comment]
My bad, looks like this was already documented: https://github.com/choojs/choo#appmountselector

>Returns `this`, so you can easily export the application for server side rendering:
>```js
>module.exports = app.mount('body')
>```

**Pull request merged**
